name: scalafmt

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  scalafmt-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install scalaftm 3.5.2
        run: |
          VERSION=3.5.2
          INSTALL_LOCATION=/var/tmp/scalafmt-native
          curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | \
            bash -s -- $VERSION $INSTALL_LOCATION
      - name: Check for scalafmt conformance
        run: /var/tmp/scalafmt-native --list --non-interactive